Repository UPC/ravada, pull requests merged in 2018-06, with the labels that each got.

#778 feat(frontend): dynamic list bases
  lib/Ravada/I18N/en.po
  public/js/ravada.js
  rvd_front.pl
  templates/main/list_bases_ng.html.ep
  templates/main/list_bases_ng_head.html.ep
  templates/main/run_request.html.ep
Labels: enhancement, frontEnd

#784 fix(frontend): create another if not suitable clone
  rvd_front.pl
Labels: frontEnd

#776 feat(backend): check free memory
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/vm/m10_freemem.t
  templates/main/run_request.html.ep
Labels: enhancement

#786 671 USB hardware change from frontend
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Front.pm
  lib/Ravada/Front/Domain/KVM.pm
  lib/Ravada/Request.pm
  rvd_front.pl
  t/front/30_controllers.t
  t/request/30_hardware.t
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/vm_hardware.html.ep
Labels: backend, enhancement, frontEnd

#768 fix(frontend): remove clones
  t/vm/20_base.t
  t/vm/v10_volatile.t
Labels: backend

#807 Years of Perl development
  index.html
Labels: documentation

#810 808 stats
  README.md
  templates/bootstrap/footer.html.ep
Labels: bug, frontEnd
