Repository UPC/ravada, pull requests merged in 2018-04, with the labels that each got.

#643 [#631] Changed version number in spice.reg file
  docs/docs/spice.reg
Labels: documentation

#632 [#631] Removed virt viewer version number
  lib/Ravada/I18N/ca.po
  templates/main/requirements.html.ep
Labels: frontEnd

#644 [#631] Removed virt viewer version number
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/de.po
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/es.po
  lib/Ravada/I18N/hi.po
  lib/Ravada/I18N/jp.po
  lib/Ravada/I18N/pt.po
  templates/main/requirements.html.ep
Labels: frontEnd

#648 footer included instead of hardcoded
  templates/main/start.html.ep
Labels: frontEnd

#654 [#649] ldap
  bin/rvd_back.pl
  lib/Ravada/Auth/LDAP.pm
  t/65_user_ldap.t
Labels: backend

#657 [#649] ldap
  bin/rvd_back.pl
  lib/Ravada/Auth.pm
  lib/Ravada/Auth/LDAP.pm
Labels: backend

#661 [#649] ldap
  .gitignore
  lib/Ravada/Auth.pm
  lib/Ravada/Front.pm
  t/60_user_sql.t
  t/front/60_ldap.t
Labels: frontEnd

#664 [#649] retry if LDAP server returns error
  lib/Ravada/Auth/LDAP.pm
Labels: frontEnd

#673 670 usbctrl
  MANIFEST
  etc/xml/dsl-i386.xml
  etc/xml/jessie-i386.xml
  etc/xml/miniremix-volume.xml
  etc/xml/sarah64-volume.xml
  etc/xml/win10.xml
  etc/xml/win7pro-volume.xml
  etc/xml/win7pro.xml
  etc/xml/win8.1-volume.xml
  etc/xml/win8.1.xml
Labels: enhancement

#687 feat(backend): migrate back
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Request.pm
  t/kvm/n10_nodes.t
Labels: backend

#695 feat: show remote client connection status
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Front.pm
  lib/Ravada/Front/Domain.pm
  templates/main/admin_machines.html.ep
Labels: enhancement

#691 fix(frontend): noadmin
  lib/Ravada.pm
  lib/Ravada/Auth/SQL.pm
  rvd_front.pl
  t/user/20_grants.t
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/vm_options.html.ep
  templates/main/vm_remove.html.ep
  templates/main/vm_screenshot.html.ep
Labels: frontEnd

#690 test: remove old volumes from multiple storage pools
  t/lib/Test/Ravada.pm
Labels: test

#694 [#646] fix(locales)
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/de.po
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/es.po
  lib/Ravada/I18N/fa.po
  lib/Ravada/I18N/fr.po
  lib/Ravada/I18N/gl.po
  lib/Ravada/I18N/hi.po
  lib/Ravada/I18N/id.po
  lib/Ravada/I18N/jp.po
  lib/Ravada/I18N/pt.po
  t/90_pos.t
  templates/bootstrap/new_user.html.ep
  templates/main/admin_machines.html.ep
  templates/main/list_bases2.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/vm_graphics.html.ep
  templates/main/vm_remove.html.ep
  templates/ng-templates/new_machine_template.html.ep
  templates/ng-templates/new_user.html.ep
Labels: frontEnd

#697 feat(cli): manage disconnected machines
  bin/rvd_back.pl
  lib/Ravada.pm
Labels: backend, enhancement

#689 test(machine): status of volatile machines
  lib/Ravada/Domain.pm
  lib/Ravada/VM/Void.pm
  t/vm/v20_volatile_clones.t
Labels: enhancement

#683 docs: update installation instructions for Fedora
  docs/docs/INSTALL_Fedora.rst
Labels: documentation

#705 fix(i18n) ja.po
  lib/Ravada/I18N/ja.po
  templates/bootstrap/user_settings.html.ep
Labels: enhancement
