Repository UPC/ravada, pull requests merged in 2018-03, with the labels that each got.

#592 589 autostart
  etc/rvd_front.conf.example
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Front.pm
  lib/Ravada/Request.pm
  public/js/admin.js
  rvd_front.pl
  t/vm/a10_autostart.t
  templates/main/admin_machines.html.ep
Labels: enhancement

#594 572 mock
  t/front/40_list_domains.t
  t/lib/Test/Ravada.pm
  t/vm/v10_volatile.t
  t/vm/z_101.t
Labels: test

#598 [#596] fetch md5sums from the same URL as the ISO
  sql/data/insert_iso_images.sql
Labels: frontEnd

#601 [#597] iptables
  lib/Ravada/Domain.pm
  t/vm/90_fw.t
Labels: bug

#603 562 nice
  templates/bootstrap/scripts.html.ep
  templates/main/vm_description.html.ep
Labels: frontEnd

#604 562 nice
  templates/bootstrap/scripts.html.ep
  templates/main/vm_description.html.ep
Labels: frontEnd

#605 [#559]I have added the option to customize the footer
  etc/rvd_front.conf.example
  rvd_front.pl
  templates/bootstrap/user_settings.html.ep
  templates/main/about.html.ep
  templates/main/admin_machines.html.ep
  templates/main/admin_messages.html.ep
  templates/main/admin_users.html.ep
  templates/main/list_bases.html.ep
  templates/main/list_bases2.html.ep
  templates/main/new_machine.html.ep
  templates/main/requirements.html.ep
  templates/main/settings.html.ep
Labels: enhancement, frontEnd

#613 [#597] iptables
  lib/Ravada/Domain.pm
  t/vm/90_fw.t
Labels: backend

#615 597 iptables
  lib/Ravada/Domain.pm
  t/lib/Test/Ravada.pm
  t/vm/90_fw.t
Labels: backend

#618 597 iptables
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Front/Domain.pm
  t/kvm/p10_password.t
  t/vm/90_fw.t
  t/vm/91_fw_req.t
Labels: backend

#622 589 autostart 2
  etc/rvd_front.conf.example
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Front.pm
  lib/Ravada/Front/Domain.pm
  lib/Ravada/Request.pm
  public/js/admin.js
  rvd_front.pl
  t/vm/a10_autostart.t
  templates/main/admin_machines.html.ep
Labels: backend

#623 [#620] Update class name
  templates/main/requirements.html.ep
Labels: bug, frontEnd

#624 [#616] hidden options
  etc/rvd_front.conf.example
Labels: documentation, enhancement

#625 [#231] grant prepare base
  lib/Ravada/Auth/SQL.pm
  lib/Ravada/Domain.pm
  rvd_front.pl
  t/30_request.t
  t/70_networks.t
  t/kvm/20_domain_kvm.t
  t/kvm/22_domain_kvm_base.t
  t/kvm/30_request.t
  t/kvm/40_import.t
  t/kvm/50_double_pci.t
  t/kvm/55_xp.t
  t/kvm/71_description_clones.t
  t/kvm/a10_pools.t
  t/kvm/a20_xml.t
  t/request/40_base.t
  t/user/20_grants.t
  t/vm/10_domain.t
  t/vm/20_base.t
  t/vm/30_remove.t
  t/vm/40_volumes.t
  t/vm/55_rename.t
  t/vm/60_dom_settings.t
  t/vm/70_clone.t
  t/vm/95_spinoff.t
Labels: enhancement

#627 626 refresh
  README.md
  bin/rvd_back.pl
  lib/Ravada.pm
  lib/Ravada/Front.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/front/40_list_domains.t
Labels: frontEnd

#636 635 grant create
  lib/Ravada.pm
  lib/Ravada/VM.pm
  sql/data/insert_grant_types.sql
  t/30_request.t
  t/70_networks.t
  t/front/10_load.t
  t/front/20_create_domain.t
  t/front/30_show_domain.t
  t/front/40_list_domains.t
  t/kvm/20_domain_kvm.t
  t/kvm/22_domain_kvm_base.t
  t/kvm/25_domain_kvm_dothings.t
  t/kvm/30_request.t
  t/kvm/40_import.t
  t/kvm/57_custom_iso.t
  t/kvm/65_dom_settings_req.t
  t/kvm/70_description.t
  t/kvm/71_description_clones.t
  t/kvm/a10_pools.t
  t/kvm/a20_xml.t
  t/kvm/p10_password.t
  t/kvm/s10_spice.t
  t/request/40_base.t
  t/user/10_domains.t
  t/user/20_grants.t
  t/vm/10_domain.t
  t/vm/20_base.t
  t/vm/30_remove.t
  t/vm/40_volumes.t
  t/vm/50_info.t
  t/vm/55_rename.t
  t/vm/60_dom_settings.t
  t/vm/60_new_args.t
  t/vm/70_clone.t
  t/vm/90_fw.t
  t/vm/91_fw_req.t
  t/vm/95_spinoff.t
  t/vm/h20_hybernate_req.t
Labels: backend

#638 [#635] grant create frontend
  lib/Ravada/Auth/SQL.pm
  rvd_front.pl
  t/55_freemem.t
  t/user/20_grants.t
  templates/main/admin_machines.html.ep
  templates/ng-templates/new_machine.html.ep
Labels: frontEnd

#640 [#583] sync back
  lib/Ravada/Domain.pm
  lib/Ravada/VM.pm
  t/kvm/n10_nodes.t
  t/kvm/n20_nodes_hibernate.t
  t/lib/Test/Ravada.pm
Labels: backend

#642 641 defunct
  bin/rvd_back.pl
  lib/Ravada.pm
Labels: backend
