Repository UPC/ravada, pull requests merged in 2018-10, with the labels that each got.

#861 fix(frontend):upgrade jquery version
  package.json
  templates/bootstrap/scripts.html.ep
Labels: frontEnd, hacktoberfest

#863 feat(i18n):update ca & es
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/es.po
Labels: frontEnd, hacktoberfest

#868 Feat/865 volatile remote
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  public/js/ravada.js
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  templates/main/vm_base.html.ep
Labels: hacktoberfest

#875 add indonesia translation
  lib/Ravada/I18N/id.po
Labels: hacktoberfest, translation

#877 fix(i18n): id.po remove repeated entries
  lib/Ravada/I18N/id.po
Labels: enhancement, frontEnd, hacktoberfest

#869 825 dist linux
  etc/xml/alpine-amd64.xml
  etc/xml/alpine-i386.xml
  etc/xml/alpine381_32-volume.xml
  etc/xml/alpine381_64-volume.xml
  etc/xml/mint19-i386.xml
  etc/xml/mint19_32-volume.xml
  lib/Ravada.pm
Labels: frontEnd, hacktoberfest

#885 wip(i18n): Add Chinese po files for China & Taiwan
  lib/Ravada/I18N/zh_CN.po
  lib/Ravada/I18N/zh_TW.po
Labels: frontEnd, hacktoberfest

#884 fix(frontend): form new node
  lib/Ravada/I18N/en.po
  templates/main/new_node.html.ep
Labels: frontEnd

#889 [#645] LDAP posix group documentation
  docs/docs/auth_ldap.rst
Labels: documentation

#891 Updated INSTALL.rst
  docs/docs/INSTALL.rst
Labels: hacktoberfest

#898 Improve French translation
  lib/Ravada/I18N/fr.po
Labels: translation

#909 fix(frontend):broken badge
  templates/bootstrap/footer.html.ep
Labels: frontEnd

#912 feature: new button remove node
  lib/Ravada/Front.pm
  lib/Ravada/VM.pm
  public/js/admin.js
  rvd_front.pl
  templates/main/admin_nodes.html.ep
Labels: frontEnd, hacktoberfest
