Repository UPC/ravada, pull requests merged in 2018-02, with the labels that each got.

#546 545 active
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Request.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/Void.pm
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
Labels: backend

#549 474 vv
  lib/Ravada/Domain.pm
Labels: backend

#556 555 ssh
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/kvm/n10_nodes.t
  t/kvm/n30_nodes_front.t
  t/lib/Test/Ravada.pm
  t/vm/r10_remote.t
Labels: backend

#558 [#557] Add Ubuntu Mate
  lib/Ravada.pm
Labels: frontEnd

#563 [#562] Add rich text editing in description tab
  templates/bootstrap/scripts.html.ep
  templates/main/run.html.ep
  templates/main/vm_description.html.ep
Labels: frontEnd

#561 [#525]Placeholder fixed
  templates/main/admin_users.html.ep
Labels: frontEnd

#560 447 min disk
  lib/Ravada.pm
  public/js/admin.js
  sql/data/insert_iso_images.sql
  sql/mysql/iso_images.sql
  templates/ng-templates/new_machine_template.html.ep
Labels: frontEnd

#565 564 nat
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  t/vm/n10_nat.t
Labels: backend, enhancement

#569 [#554] base swap
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  t/kvm/71_description_clones.t
  t/vm/20_base.t
  t/vm/40_volumes.t
Labels: backend

#570 [#564] [doc] nat_ip usage
  lib/Ravada/VM.pm
Labels: documentation

#576 [#575] new field internal id
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  sql/mysql/domains.sql
  sql/sqlite/domains.sql
  t/vm/10_domain.t
Labels: backend

#578 [#575] [test] internal id on active domains
  t/front/20_create_domain.t
  t/vm/10_domain.t
Labels: test

#579 [#575] update the internal id on domain startup
  lib/Ravada/Domain.pm
  lib/Ravada/Front.pm
  t/front/20_create_domain.t
  t/front/40_list_domains.t
Labels: frontEnd

#580 547 remote
  bin/rvd_back.pl
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Front.pm
  lib/Ravada/Request.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  rvd_front.pl
  t/35_request_start.t
  t/kvm/22_domain_kvm_base.t
  t/kvm/n10_nodes.t
  t/kvm/n30_nodes_front.t
  t/lib/Test/Ravada.pm
  t/request/40_base.t
  t/vm/60_new_args.t
  t/vm/h20_hybernate_req.t
Labels: backend, enhancement

#582 547 remote
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Request.pm
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
Labels: backend, enhancement
