Repository UPC/ravada, pull requests merged in 2018-05, with the labels that each got.

#718 fix(test): run tests with non-root user
  Makefile.PL
  lib/Ravada/Domain.pm
  t/front/60_ldap.t
  t/vm/n10_nat.t
  t/vm/n20_name.t
Labels: test

#716 fix(frontend): check admin rights
  rvd_front.pl
  templates/ng-templates/new_user.html.ep
Labels: frontEnd, security

#714 646 check po
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/es.po
  templates/main/about.html.ep
  templates/main/admin_machines.html.ep
  templates/main/admin_messages.html.ep
  templates/main/requirements.html.ep
  templates/main/settings_machine.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/vm_options.html.ep
  templates/ng-templates/new_user.html.ep
Labels: enhancement, frontEnd

#724 fix(backend): use default defined storage
  lib/Ravada/VM/KVM.pm
  t/kvm/a10_pools.t
Labels: backend

#727 test(backend): test base prepared in default storage
  lib/Ravada/VM/KVM.pm
  t/kvm/a10_pools.t
Labels: test

#734 #629 clean
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  sql/mysql/domains_kvm.sql
  sql/mysql/domains_void.sql
  sql/sqlite/domains_kvm.sql
  sql/sqlite/domains_void.sql
  t/vm/v10_volatile.t
  t/vm/v20_volatile_clones.t
Labels: backend

#745 fix(users): revoke only enabled grants
  lib/Ravada/Auth/SQL.pm
  t/user/50_admin.t
Labels: bug

#735 #629 clean
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  rvd_front.pl
  sql/mysql/domains_kvm.sql
  sql/mysql/domains_void.sql
  sql/sqlite/domains_kvm.sql
  sql/sqlite/domains_void.sql
  t/vm/v10_volatile.t
  t/vm/v20_volatile_clones.t
Labels: backend

#743 #739 shutdown clones
  lib/Ravada.pm
  lib/Ravada/Auth/SQL.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Front.pm
  lib/Ravada/Request.pm
  rvd_front.pl
  t/35_request_start.t
  t/user/20_grants.t
  t/user/30_grant_remove.t
  t/user/40_grant_shutdown.t
  t/vm/20_base.t
  t/vm/t10_timeout.t
Labels: enhancement, frontEnd
