Repository UPC/ravada, pull requests merged in 2018-11, with the labels that each got.

#925 Feature #916 configure access
  lib/Ravada.pm
  lib/Ravada/Auth/LDAP.pm
  lib/Ravada/Auth/User.pm
  lib/Ravada/Domain.pm
  public/js/ravada.js
  rvd_front.pl
  sql/mysql/access_ldap_attribute.sql
  t/front/70_ldap_access.t
  templates/bootstrap/user_settings.html.ep
  templates/main/machine_access.html.ep
  templates/main/machine_access_list.html.ep
  templates/main/machine_access_new.html.ep
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
Labels: frontEnd

#931 fix option to active autostart machines
  templates/main/admin_machines.html.ep
Labels: frontEnd

#938 Feature/918 pxe
  etc/xml/empty-amd64.xml
  etc/xml/empty-i386.xml
  lib/Ravada.pm
  templates/ng-templates/new_machine_template.html.ep
Labels: enhancement, frontEnd

#945 927 fix html
  templates/bootstrap/navigation.html.ep
  templates/bootstrap/user_settings.html.ep
  templates/main/list_bases_ng.html.ep
  templates/main/show_requests.html.ep
  templates/main/vm_remove.html.ep
  templates/ng-templates/new_machine_other.html.ep
Labels: frontEnd

#946 921 outdated files
  public/css/sb-admin-rtl.css
  rvd_front.pl
  templates/bootstrap/login.html.ep
  templates/main/list_bases.html.ep
  templates/main/list_bases2.html.ep
  templates/main/settings.html.ep
Labels: frontEnd

#948 866 bootstrap4
  lib/Ravada/I18N/en.po
  package.json
  public/css/main.css
  public/css/sb-admin.css
  templates/bootstrap/footer.html.ep
  templates/bootstrap/header.html.ep
  templates/bootstrap/navigation.html.ep
  templates/bootstrap/new_user.html.ep
  templates/bootstrap/new_user_ok.html.ep
  templates/bootstrap/scripts.html.ep
  templates/bootstrap/user_settings.html.ep
  templates/main/about.html.ep
  templates/main/admin_machines.html.ep
  templates/main/admin_messages.html.ep
  templates/main/admin_nodes.html.ep
  templates/main/admin_users.html.ep
  templates/main/list_bases_ng.html.ep
  templates/main/list_bases_ng_head.html.ep
  templates/main/manage_user.html.ep
  templates/main/manage_user_admin.html.ep
  templates/main/manage_user_grants.html.ep
  templates/main/new_node.html.ep
  templates/main/request.html.ep
  templates/main/requirements.html.ep
  templates/main/run_request.html.ep
  templates/main/settings_machine.html.ep
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/show_requests.html.ep
  templates/main/start.html.ep
  templates/main/vm_base.html.ep
  templates/main/vm_copy.html.ep
  templates/main/vm_description.html.ep
  templates/main/vm_drivers.html.ep
  templates/main/vm_graphics.html.ep
  templates/main/vm_hardware.html.ep
  templates/main/vm_options.html.ep
  templates/main/vm_remove.html.ep
  templates/main/vm_rename.html.ep
  templates/main/vm_screenshot.html.ep
  templates/ng-templates/new_machine.html.ep
  templates/ng-templates/new_machine_other.html.ep
  templates/ng-templates/new_machine_template.html.ep
  templates/ng-templates/new_user.html.ep
  templates/ng-templates/user_machines.html.ep
  templates/ng-templates/user_machines_anonymous.html.ep
Labels: frontEnd

#950 Feature #947 node disable
  lib/Ravada/Domain.pm
  lib/Ravada/Front.pm
  public/js/admin.js
  rvd_front.pl
  t/nodes/30_disable_node.t
  templates/main/admin_nodes.html.ep
Labels: enhancement

#957 Fix #955 spice
  lib/Ravada/Domain/KVM.pm
  t/kvm/p10_password.t
Labels: frontEnd
