Repository UPC/ravada, pull requests merged in 2019-03, with the labels that each got.

#997 Feature/996 new permission to rename
  lib/Ravada.pm
  lib/Ravada/Auth/SQL.pm
  rvd_front.pl
  t/user/25_grant_rename.t
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
Labels: frontEnd

#1019 Feature #1104 storage
  lib/Ravada/Domain.pm
  lib/Ravada/VM.pm
  t/kvm/n10_nodes.t
  t/user/30_grant_remove.t
Labels: enhancement

#1020 Feature #1010 smbios
  lib/Ravada/VM/KVM.pm
  t/kvm/s20_sysinfo.t
  t/user/40_grant_shutdown.t
Labels: backend

#1021 Feat/1015 anonymous timeout
  public/js/ravada.js
  rvd_front.pl
  templates/main/run_request.html.ep
Labels: frontEnd

#1022 fix: screenshot image anonymous
  lib/Ravada/Front.pm
  rvd_front.pl
Labels: frontEnd

#1029 Fix #1026 remove
  lib/Ravada/Domain.pm
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  t/nodes/50_three_nodes.t
Labels: backend
