Repository UPC/ravada, pull requests merged in 2019-04, with the labels that each got.

#1038 fix(frontend): Upgrade bootstrap & ckeditor js
  package.json
  templates/bootstrap/header.html.ep
  templates/bootstrap/scripts.html.ep
Labels: frontEnd

#1040 Refactor #10 disk
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/kvm/a10_pools.t
  t/vm/40_volumes.t
Labels: backend, enhancement

#1046 refactor(requests): run request after_request
  lib/Ravada.pm
  lib/Ravada/Request.pm
Labels: backend, enhancement

#1049 fix(i18n): Update translations from Transifex
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/es.po
Labels: translation

#1050 fix(i18): hardcoded
  lib/Ravada/I18N/en.po
  templates/main/start.html.ep
Labels: translation

#1056 Fix/1028 i18n messages
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/es.po
Labels: translation

#1058 feat(i18n): Uptade translations & italian language
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/fr.po
  lib/Ravada/I18N/it.po
  lib/Ravada/I18N/ja.po
  templates/bootstrap/user_settings.html.ep
Labels: translation

#1061 Feature #1041 display ip
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  t/vm/90_fw.t
  t/vm/n10_nat.t
Labels: backend, enhancement

#1066 Feature #763 config
  lib/Ravada.pm
  t/02_config.t
  t/README_nodes.md
Labels: backend

#1070 test(nodes): testing remote nodes
  t/README_nodes.md
  t/lib/Test/Ravada.pm
  t/nodes/30_disable_node.t
  t/nodes/50_three_nodes.t
Labels: test

#1075 feature(backend): remove unnecessary down req
  lib/Ravada.pm
Labels: backend
