Repository UPC/ravada, pull requests merged in 2019-10, with the labels that each got.

#1160 User experience access directly to virtual desktop if only has one machine
  rvd_front.pl
Labels: enhancement, frontEnd

#1165 Update windows_clients.rst
  docs/docs/windows_clients.rst
Labels: documentation

#1179 fix(docker): latest tag not exist yet
  dockerfy/docker-compose.yml
Labels: enhancement

#1186 Fix/1185 update cancel hyperlink
  templates/main/manage_user_admin.html.ep
  templates/main/manage_user_grants.html.ep
Labels: frontEnd

#1176 Feature/1145 directly
  lib/Ravada/Auth/User.pm
  rvd_front.pl
  t/65_user_ldap.t
Labels: frontEnd
