Repository UPC/ravada, pull requests merged in 2020-12, with the labels that each got.

#1455 Translations update from Weblate
  lib/Ravada/I18N/it.po
Labels: localization

#1460 Fix spice password
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/VM.pm
  t/kvm/n10_nodes.t
  t/kvm/p10_password.t
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  t/nodes/20_dead_node.t
  t/vm/n10_nat.t
  templates/main/admin_settings.html.ep
Labels: security

#1321 Feature node and network settings
  lib/Ravada.pm
  lib/Ravada/Front.pm
  lib/Ravada/Request.pm
  lib/Ravada/VM.pm
  lib/Ravada/WebSocket.pm
  public/css/main.css
  public/js/admin.js
  script/rvd_front
  t/70_networks.t
  t/kvm/a10_pools.t
  t/lib/Test/Ravada.pm
  t/mojo/10_login.t
  t/mojo/30_settings.t
  templates/bootstrap/navigation.html.ep
  templates/main/admin_machines.html.ep
  templates/main/admin_networks.html.ep
  templates/main/admin_nodes.html.ep
  templates/main/network_machines.html.ep
  templates/main/network_new.html.ep
  templates/main/network_options.html.ep
  templates/main/network_remove.html.ep
  templates/main/new_node.html.ep
  templates/main/node_bases.html.ep
  templates/main/node_options.html.ep
  templates/main/node_remove.html.ep
  templates/main/settings_generic.html.ep
  templates/main/settings_generic_tabs.html.ep
  templates/main/vm_remove.html.ep
Labels: frontEnd

#1468 fix(auth): continue with match if bind failed
  lib/Ravada/Auth/LDAP.pm
Labels: frontEnd
