Repository UPC/ravada, pull requests merged in 2020-01, with the labels that each got.

#1227 Refactor #1196 ping
  lib/Ravada/Front.pm
  lib/Ravada/WebSocket.pm
  public/js/admin.js
  public/js/ravada.js
  rvd_front.pl
Labels: backend

#1233 Feature restrict access by client
  lib/Ravada/Domain.pm
  lib/Ravada/Front.pm
  lib/Ravada/WebSocket.pm
  public/js/ravada.js
  rvd_front.pl
  sql/mysql/domain_access.sql
  sql/sqlite/domain_access.sql
  t/front/80_access.t
  t/kvm/a20_xml.t
  t/mojo/20_ws.t
  templates/main/machine_access.html.ep
  templates/main/machine_access_client.html.ep
  templates/main/machine_access_client_list.html.ep
  templates/main/machine_access_client_new.html.ep
  templates/main/machine_access_client_verify.html.ep
  templates/main/machine_access_ldap.html.ep
  templates/main/machine_access_ldap_list.html.ep
  templates/main/machine_access_ldap_new.html.ep
  templates/main/settings_machine_tabs_head.html.ep
Labels: enhancement, frontEnd

#1234 Copy screenshot updated to db
  lib/Ravada.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Front.pm
  lib/Ravada/Request.pm
  public/js/ravada.js
  rvd_front.pl
  templates/main/vm_screenshot.html.ep
Labels: frontEnd

#1232 Fix/1201 renew mac
  lib/Ravada/VM/KVM.pm
  t/kvm/72_add_nic.t
Labels: backend, bug
