Repository UPC/ravada, pull requests merged in 2020-06, with the labels that each got.

#1347 fix(nodes): balance create volatile machines
  lib/Ravada.pm
  lib/Ravada/VM.pm
  t/nodes/10_basic.t
Labels: backend

#1348 feature(frontend): use Mojo log in frontend
  script/rvd_front
Labels: frontEnd

#1349 Feature maintenance mode
  lib/Ravada.pm
  lib/Ravada/Front.pm
  public/js/admin.js
  script/rvd_front
  t/front/80_access.t
  templates/main/admin_settings.html.ep
Labels: frontEnd

#1354 refactor: change box position to ask first the current password
  templates/bootstrap/user_settings.html.ep
Labels: frontEnd

#1355 Fix/1352 check current password
  script/rvd_front
Labels: security

#1362 refactor(frontend): language settings improved
  script/rvd_front
  templates/bootstrap/user_settings.html.ep
Labels: translation
