Repository UPC/ravada, pull requests merged in 2020-05, with the labels that each got.

#1329 fix(doc): update version spice in reg file
  docs/docs/spice.reg
Labels: documentation

#1318 Feat/1317 description
  lib/Ravada/Front.pm
  lib/Ravada/I18N/en.po
  public/css/sb-admin.css
  public/js/ravada.js
  templates/main/list_bases_ng.html.ep
Labels: frontEnd

#1330 Feature limit started machines per user
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  script/rvd_front
  templates/main/admin_settings.html.ep
Labels: enhancement

#1334 doc: mysql install
  docs/docs/INSTALL_devel.rst
  docs/docs/INSTALL_mysql.rst
Labels: documentation

#1253 Fixed browser language ca-valencia
  lib/Ravada/I18N/ca-valencia.po
  sudo
  templates/bootstrap/user_settings.html.ep
  templates/sudo
Labels: translation

#1336 Fix locked in admin machines
  lib/Ravada.pm
  t/request/30_hardware.t
Labels: frontEnd

#1332 Add Android KVM Template Androidx86
  etc/xml/android-amd64.xml
  etc/xml/android-volume.xml
  etc/xml/focal_fossa-amd64.xml
  etc/xml/focal_fossa64-volume.xml
  lib/Ravada.pm
Labels: enhancement

#1343 Refactor use net::openssh library
  Makefile.PL
  debian/control-debian-10
  debian/control-ubuntu-18.04
  debian/control-ubuntu-19.04
  debian/control-ubuntu-20.04
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  t/nodes/30_start_stop.t
Labels: backend
