Repository UPC/ravada, pull requests merged in 2020-11, with the labels that each got.

#1423 feature(frontend): Add weblate badge
  templates/bootstrap/footer.html.ep
Labels: frontEnd

#1424 Translations update from Weblate
  lib/Ravada/I18N/ca-valencia.po
  lib/Ravada/I18N/es.po
  lib/Ravada/I18N/gl.po
  lib/Ravada/I18N/ja.po
Labels: localization

#1427 Translations update from Weblate
  lib/Ravada/I18N/de.po
Labels: localization

#1431 Translations update from Weblate
  lib/Ravada/I18N/en.po
Labels: localization

#1430 Feature/1419 chatwoot
  etc/rvd_front.conf.example
  public/js/custom/insert_here_widget.js
  script/rvd_front
  templates/bootstrap/scripts.html.ep
Labels: frontEnd

#1434 Translations update from Weblate
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/gl.po
Labels: localization

#1436 refactor(test): use a pre-created base to test
  lib/Ravada/Domain.pm
  t/vm/92_ports.t
Labels: test

#1441 Translations update from Weblate
  lib/Ravada/I18N/de.po
Labels: localization

#1444 Translations update from Weblate
  lib/Ravada/I18N/gl.po
Labels: localization

#1445 Add buttons tab
  lib/Ravada/Domain.pm
  lib/Ravada/Front.pm
  public/js/ravada.js
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
  templates/main/vm_actions.html.ep
Labels: frontEnd

#1449 fix(typo): remove extra character
  docs/docs/create_cert.sh
Labels: bug

#1451 fix(pools): auto-number even with only one clone
  lib/Ravada.pm
Labels: backend, bug

#1453 Feature: compact
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Request.pm
  lib/Ravada/VM.pm
  lib/Ravada/Volume/Class.pm
  lib/Ravada/Volume/QCOW2.pm
  lib/Ravada/Volume/Void.pm
  script/rvd_front
  t/lib/Test/Ravada.pm
  t/vm/compact.t
  templates/main/vm_actions.html.ep
Labels: enhancement
