Repository UPC/ravada, pull requests merged in 2020-10, with the labels that each got.

#1390 Fix backingstore
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Volume/QCOW2.pm
  t/lib/Test/Ravada.pm
  t/vm/40_volumes.t
  t/vm/45_vol_swap.t
Labels: backend, hacktoberfest

#1393 Feature migrate machine
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Request.pm
  public/js/ravada.js
  script/rvd_back
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  templates/main/admin_machines.html.ep
  templates/main/vm_options.html.ep
Labels: hacktoberfest

#1395 test(auth): check that login fails properly
  script/rvd_front
  t/40_auth_sql.t
  t/lib/Test/Ravada.pm
  t/mojo/10_login.t
  t/mojo/20_ws.t
Labels: hacktoberfest, test

#1391 Save LDAP errors in $ldap_err to reduce noise in logs
  lib/Ravada/Auth.pm
Labels: hacktoberfest

#1398 Docs for cas login
  docs/docs/cas_login.rst
  docs/index.rst
Labels: documentation, hacktoberfest

#1376 modified docker files for tzdata package compatibility
  dockerfy/docker-compose.yml
  dockerfy/dockers/back/Dockerfile
  dockerfy/dockers/front/Dockerfile
Labels: dockers, hacktoberfest

#1399 Update CAS docs to add logout reference
  docs/docs/cas_login.rst
Labels: documentation

#1400 Fix nodes nat
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/VM.pm
  public/js/admin.js
  t/nodes/10_basic.t
Labels: hacktoberfest

#1405 feat(grant): Add more option to grant
  templates/main/vm_options.html.ep
Labels: enhancement, hacktoberfest

#1406 Refactor/1389 shutdown clones
  lib/Ravada/I18N/en.po
  templates/main/vm_clones.html.ep
Labels: frontEnd, hacktoberfest

#1408 Refactor/1407 action buttons
  lib/Ravada/Request.pm
  public/js/ravada.js
  script/rvd_front
  templates/main/list_bases_ng.html.ep
Labels: frontEnd, hacktoberfest

#1411 bug(dockers): fix some things in docker files
  dockerfy/.env
  dockerfy/docker-compose.yml
  dockerfy/dockers/back/Dockerfile
  dockerfy/dockers/front/Dockerfile
Labels: bug, hacktoberfest

#1415 feature(localization): add template file
  lib/Ravada/I18N/messages.pot
Labels: hacktoberfest, localization
