Repository UPC/ravada, pull requests merged in 2020-07, with the labels that each got.

#1370 Fix/1344 upgrade libs
  dockerfy/dockers/back/Dockerfile
  dockerfy/dockers/front/Dockerfile
Labels: dockers

#1371 fix(docker): port conflict
  dockerfy/docker-compose.yml
  dockerfy/dockers/back/Dockerfile
Labels: enhancement

#1375 Update bootstrap-select version
  etc/fallback.conf
  package.json
  templates/bootstrap/header.html.ep
  templates/bootstrap/scripts.html.ep
Labels: frontEnd

#1374 Feature support focal fossa server
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/VM.pm
  lib/Ravada/Volume/QCOW2.pm
  t/20_volumes.t
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
  t/nodes/10_basic.t
  t/vm/92_ports.t
Labels: backend

#1378 fix(frontend): set timeout admin longer in management
  etc/rvd_front.conf.example
  script/rvd_front
Labels: frontEnd

#1379 refactor(backend): clean iptables table
  lib/Ravada/Domain.pm
  t/vm/90_fw.t
Labels: backend
