Repository UPC/ravada, pull requests merged in 2020-04, with the labels that each got.

#1288 feat(settings): Shutdown all clones from settings
  lib/Ravada.pm
  lib/Ravada/Request.pm
  lib/Ravada/VM.pm
  t/vm/10_domain.t
  templates/main/vm_clones.html.ep
Labels: enhancement, frontEnd

#1290 Fix/1270 dockers
  dockerfy/.env
  dockerfy/docker-compose.yml
  dockerfy/dockers/back/supervisord.conf
  dockerfy/dockers/front/Dockerfile
  dockerfy/dockers/front/supervisord.conf
Labels: bug

#1293 Fix renamed vol
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/VM/Void.pm
  lib/Ravada/Volume.pm
  lib/Ravada/Volume/Class.pm
  t/kvm/n20_nodes_hibernate.t
  t/nodes/10_basic.t
  t/nodes/60_hardware.t
  t/vm/10_domain.t
  t/vm/30_remove.t
  t/vm/35_remove2.t
Labels: backend

#1296 Refactor admin machines
  lib/Ravada.pm
  lib/Ravada/Front.pm
  lib/Ravada/WebSocket.pm
  public/js/admin.js
  public/js/ravada.js
  script/rvd_front
  templates/main/admin_machines.html.ep
  templates/main/vm_options.html.ep
Labels: frontEnd

#1301 Fix node out of memory
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/55_freemem.t
  t/lib/Test/Ravada.pm
  t/mojo/20_ws.t
  t/nodes/10_basic.t
Labels: backend
