Repository UPC/ravada, pull requests merged in 2021-01, with the labels that each got.

#1474 fix(frontend): jquery bug
  templates/bootstrap/scripts.html.ep
Labels: bug, frontEnd

#1471 fix(dockers): read env file
  dockerfy/docker-compose.yml
Labels: bug, dockers

#1479 Fix #1478 link
  lib/Ravada/Volume.pm
  t/20_volumes.t
Labels: backend

#1484 Changes the vm is running error width
  templates/main/vm_rename.html.ep
Labels: frontEnd

#1486 Feature: refresh ports
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Request.pm
  lib/Ravada/WebSocket.pm
  public/js/ravada.js
  templates/main/run_request.html.ep
Labels: enhancement

#1487 doc: Reset branch to upstream develop
  CONTRIBUTING.md
Labels: documentation

#1485 new clone name takes into account the already created clones
  lib/Ravada.pm
Labels: backend
