Repository UPC/ravada, pull requests merged in 2021-03, with the labels that each got.

#1491 Disable reboot buttons if domain not active
  script/rvd_front
Labels: frontEnd

#1516 fix(1515): remove bootstrap-select to fix errors
  etc/fallback.conf
  package.json
  templates/bootstrap/header.html.ep
  templates/bootstrap/scripts.html.ep
  templates/main/vm_drivers.html.ep
  templates/main/vm_graphics.html.ep
Labels: bug, frontEnd

#1517 Translations update from Weblate
  lib/Ravada/I18N/ca-valencia.po
Labels: localization
