Repository UPC/ravada, pull requests merged in 2022-10, with the labels that each got.

#1840 Consistency naming for Hybernate to Hibernate in translations
  lib/Ravada/I18N/ar.po
  lib/Ravada/I18N/ca-valencia.po
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/de.po
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/es.po
  lib/Ravada/I18N/eu.po
  lib/Ravada/I18N/fr.po
  lib/Ravada/I18N/gl.po
  lib/Ravada/I18N/he.po
  lib/Ravada/I18N/id.po
  lib/Ravada/I18N/it.po
  lib/Ravada/I18N/ja.po
  lib/Ravada/I18N/ko.po
  lib/Ravada/I18N/messages.pot
  lib/Ravada/I18N/nb_NO.po
  lib/Ravada/I18N/pt.po
  lib/Ravada/I18N/ru.po
  lib/Ravada/I18N/tr.po
  lib/Ravada/I18N/zh_CN.po
Labels: hacktoberfest, hacktoberfest-accepted

#1842 Hindi translation
  lib/Ravada/I18N/hi.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1841 i18n: German translation
  lib/Ravada/I18N/de.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1835 Translations update from Hosted Weblate
  lib/Ravada/I18N/es.po
  lib/Ravada/I18N/fr.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1844 🇳🇴 Bring Norwegian translations up to date
  lib/Ravada/I18N/nb_NO.po
Labels: hacktoberfest

#1846 Feat usb management
  lib/Ravada.pm
  lib/Ravada/Domain/KVM.pm
  lib/Ravada/Front/Domain.pm
  lib/Ravada/Front/Domain/KVM.pm
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  t/kvm/22_domain_kvm_base.t
  t/request/30_hardware.t
  t/request/32_hw_usb.t
  templates/main/manage_machine_edit.html.ep
  templates/main/manage_machine_edit_usb.html.ep
  templates/main/vm_hardware.html.ep
Labels: enhancement, backend, hacktoberfest-accepted

#1848 Update vi.po
  lib/Ravada/I18N/vi.po
Labels: hacktoberfest, hacktoberfest-accepted

#1839 Translated Chinese at 100%
  lib/Ravada/I18N/zh_CN.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1852 add Melayu translation
  lib/Ravada/I18N/my.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1861 Update italian translation
  lib/Ravada/I18N/it.po
Labels: hacktoberfest, hacktoberfest-accepted

#1859 CSP Headers
  script/rvd_front
Labels: frontEnd, hacktoberfest, hacktoberfest-accepted

#1862 fix(frontend): do not reconnect web services for proper logout
  public/js/ravada.js
Labels: hacktoberfest, hacktoberfest-accepted

#1865 feat(frontend): Show date and time of last change of state
  lib/Ravada.pm
  lib/Ravada/Domain.pm
  lib/Ravada/Domain/Void.pm
  lib/Ravada/Front.pm
  lib/Ravada/VM.pm
  templates/main/admin_machines.html.ep
  templates/main/run_request.html.ep
Labels: frontEnd, hacktoberfest, hacktoberfest-accepted

#1869 feat(net): grant open ports
  lib/Ravada.pm
  lib/Ravada/Auth/SQL.pm
  t/user/20_grants.t
  templates/main/settings_machine_tabs_body.html.ep
  templates/main/settings_machine_tabs_head.html.ep
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1874 bug(footer): info actual year
  templates/bootstrap/footer.html.ep
Labels: documentation, hacktoberfest-accepted

#1875 feat(requirements): update mac requirements info
  lib/Ravada/I18N/ca.po
  lib/Ravada/I18N/en.po
  lib/Ravada/I18N/es.po
  templates/main/requirements.html.ep
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#1872 feat(volumes): permissions to create volumes
  lib/Ravada.pm
  lib/Ravada/Auth/SQL.pm
  script/rvd_front
  t/user/20_grants.t
  templates/main/manage_user_grants.html.ep
  templates/main/run_request.html.ep
  templates/main/settings_machine_tabs_head.html.ep
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1877 Update fr.po
  lib/Ravada/I18N/fr.po
Labels: hacktoberfest, hacktoberfest-accepted

#1880 fix(clone): add some tests
  .github/workflows/github-action-test.yml
  lib/Ravada.pm
  script/rvd_front
  t/40_auth_sql.t
  t/50_images.t
  t/60_user_sql.t
  t/65_user_ldap.t
  t/front/60_ldap.t
  t/kvm/12_vm_kvm.t
  t/kvm/n10_nodes.t
  t/lib/Test/Ravada.pm
  t/mojo/10_login.t
  t/request/32_hw_usb.t
  t/vm/20_base.t
  templates/main/admin_machines.html.ep
Labels: hacktoberfest, hacktoberfest-accepted
