Repository UPC/ravada, pull requests merged in 2023-10, with the labels that each got.

#1991 Update de.po
  lib/Ravada/I18N/de.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1994 Updated the changes of pr#1993
  lib/Ravada/I18N/en.po
  templates/main/requirements.html.ep
Labels: hacktoberfest, hacktoberfest-accepted

#2000 Update Korean Translation
  lib/Ravada/I18N/ko.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#1996 Fix pool duplicated
  lib/Ravada/VM.pm
  lib/Ravada/VM/KVM.pm
  lib/Ravada/VM/Void.pm
  t/lib/Test/Ravada.pm
  t/storage_list_unused.t
  t/vm/s30_storage.t
Labels: hacktoberfest, hacktoberfest-accepted

#2002 Some more german translations
  lib/Ravada/I18N/de.po
Labels: hacktoberfest, localization, hacktoberfest-accepted

#2003 Fix/1920 csp
  .gitignore
  etc/rvd_front.conf.example
  lib/Ravada.pm
  lib/Ravada/Front.pm
  public/js/admin.js
  script/rvd_front
  t/mojo/40_security_policy.t
  templates/bootstrap/header.html.ep
  templates/main/admin_settings.html.ep
  templates/main/admin_settings_submit.html.ep
Labels: bug, hacktoberfest, hacktoberfest-accepted

#1986 fix: lock and shutdown machines before prepare
  lib/Ravada.pm
  lib/Ravada/Request.pm
  t/mojo/10_login.t
  t/mojo/20_ws.t
  t/request/40_base.t
  t/vm/70_clone.t
Labels: backend, hacktoberfest
